<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>vozoromnotna</Authors>
        <Description>UTC12 IR camera extension of AsyncCapture library</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AsyncCapture.Core\AsyncCapture.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="serialdeviceslib" Version="1.0.0" />
    </ItemGroup>

</Project>
