<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>vozoromnotna</Authors>
        <Description>GStreamer extension of AsyncCapture library</Description>
        <PackageProjectUrl>https://github.com/vozoromnotna/AsyncCapture</PackageProjectUrl>
        <RepositoryUrl>https://github.com/vozoromnotna/AsyncCapture</RepositoryUrl>
        <Version>2.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="gstreamer-sharp-netcore" Version="0.0.8" />
      <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AsyncCapture.Core\AsyncCapture.Core.csproj" />
    </ItemGroup>

</Project>
