<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>GStreamer extension of AsyncCapture library</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="gstreamer-sharp-netcore" Version="0.0.8" />
      <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AsyncCapture.Core\AsyncCapture.Core.csproj" />
    </ItemGroup>

</Project>
