<Project>
    <PropertyGroup>
        <Authors>vozoromnotna</Authors>
        <Company>STC UI RAS</Company>
        <PackageProjectUrl>https://github.com/vozoromnotna/AsyncCapture</PackageProjectUrl>
        <RepositoryUrl>https://github.com/vozoromnotna/AsyncCapture</RepositoryUrl>
        <Version>2.0.2</Version>
    </PropertyGroup>
</Project>