<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>AsyncCapture.Core</PackageId>
    <Authors>vozoromnotna</Authors>
    <Company>STC UI RAS</Company>
    <Description>A universal library for working with cameras </Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HDF5-CSharp" Version="1.19.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  
  
</Project>
